flags:
  servant-jquery:
    example: false
packages:
  - servant-examples/
  - servant-docs/
  - servant-blaze/
  - servant-client/
  - servant-js/
  - servant-lucid/
  - servant/
  - servant-server/
extra-deps:
  - doctest-0.10.1
resolver: nightly-2015-07-24
